apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gp2otw4fv-python 
  janus-idp.io/tekton: gp2otw4fv-python
  backstage.io/kubernetes-id: gp2otw4fv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gp2otw4fv-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  