apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gp2otw4fv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gp2otw4fv-python 
  name: gp2otw4fv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gp2otw4fv-python 
