apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gp2otw4fv-python-gitops
  description: This is GitOps manifest for gp2otw4fv-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: gp2otw4fv-python
    backstage.io/kubernetes-id: gp2otw4fv-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gp2otw4fv-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gp2otw4fv-python
